import type { AdminAuditLog, AdminBid, AdminMetrics, AdminOrder, AdminUser } from "./api.types";
import { formatGHS } from "./format";

interface FormattedCsvOptions {
  filename: string;
  reportTitle: string;
  subtitle?: string;
  periodLabel?: string;
  headers: string[];
  rows: (string | number | boolean | null | undefined)[][];
  totalsRow?: (string | number | boolean | null | undefined)[];
  metadata?: Record<string, string | number>;
}

export function downloadFormattedCsv({
  filename,
  reportTitle,
  subtitle = "Ghana Stock Exchange Licensed Broker & Asset Manager",
  periodLabel = "All Time",
  headers,
  rows,
  totalsRow,
  metadata = {},
}: FormattedCsvOptions) {
  const esc = (v: string | number | boolean | null | undefined): string => {
    if (v === null || v === undefined) return '""';
    const s = String(v);
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : `"${s}"`;
  };

  const now = new Date();
  const timestamp = now.toISOString().replace("T", " ").slice(0, 19) + " UTC";

  const lines: string[] = [
    `# ==============================================================================`,
    `# CONSTANT CAPITAL (GHANA) LIMITED - BROKERAGE STATEMENT`,
    `# ${subtitle}`,
    `# Report Title: ${reportTitle}`,
    `# Generated At: ${timestamp}`,
    `# Reporting Period: ${periodLabel}`,
    `# Total Records: ${rows.length}`,
    ...Object.entries(metadata).map(([k, v]) => `# ${k}: ${v}`),
    `# Classification: CONFIDENTIAL / REGULATORY REPORT`,
    `# ==============================================================================`,
    ``,
    headers.map(esc).join(","),
    ...rows.map((row) => row.map(esc).join(",")),
  ];

  if (totalsRow && totalsRow.length > 0) {
    lines.push(totalsRow.map(esc).join(","));
  }

  lines.push("");
  lines.push(
    `# End of Report — Generated by Constant Capital Constrade+ Institutional Engine`,
  );

  const csvContent = "\uFEFF" + lines.join("\r\n"); // UTF-8 BOM for Excel compatibility
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Formatted Orders & Execution Audit Export
 */
export function exportOrdersReport(orders: AdminOrder[], periodLabel = "All Time") {
  const dateStr = new Date().toISOString().slice(0, 10);
  const totalVolume = orders.reduce((sum, o) => {
    const price = Number(o.filledPrice ?? o.price ?? 0);
    const qty = Number(o.quantity ?? 0);
    return sum + (price * qty);
  }, 0);

  const estFees = totalVolume * 0.0115;

  const headers = [
    "Order ID",
    "Client",
    "Instrument",
    "Side",
    "Type",
    "Quantity / Units",
    "Target / Filled Price (GHS)",
    "Gross Notional (GHS)",
    "Est. Fee (1.15%)",
    "Status",
    "Created Date",
  ];

  const rows = orders.map((o) => {
    const price = Number(o.filledPrice ?? o.price ?? 0);
    const qty = Number(o.quantity ?? 0);
    const gross = price * qty;
    const fee = gross * 0.0115;
    return [
      o.id,
      o.client,
      o.instrument,
      o.side.toUpperCase(),
      o.order_type.toUpperCase(),
      qty.toLocaleString(),
      price.toFixed(2),
      gross.toFixed(2),
      fee.toFixed(2),
      o.status.toUpperCase(),
      new Date(o.created_at).toISOString().replace("T", " ").slice(0, 19),
    ];
  });

  const totalsRow = [
    "TOTALS / SUMMARY",
    `${orders.length} Orders`,
    "—",
    "—",
    "—",
    orders.reduce((s, o) => s + (Number(o.quantity) || 0), 0).toLocaleString(),
    "—",
    totalVolume.toFixed(2),
    estFees.toFixed(2),
    "—",
    "—",
  ];

  downloadFormattedCsv({
    filename: `constant-capital-orders-audit-${dateStr}.csv`,
    reportTitle: "Trade Execution & Order Flow Audit Report",
    periodLabel,
    headers,
    rows,
    totalsRow,
    metadata: {
      "Total Executed Volume": `GHS ${totalVolume.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      "Estimated Brokerage Revenue": `GHS ${estFees.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    },
  });
}

/**
 * Formatted Clients & KYC Registry Export
 */
export function exportClientsReport(users: AdminUser[], periodLabel = "All Time") {
  const dateStr = new Date().toISOString().slice(0, 10);
  const totalCash = users.reduce((sum, u) => sum + (Number(u.cash) || 0), 0);
  const approvedKycCount = users.filter((u) => String(u.kyc_status).toLowerCase() === "approved").length;

  const headers = [
    "Client Full Name",
    "Email Address",
    "Account Role",
    "KYC Status",
    "CSD Account Number",
    "Cash Balance (GHS)",
    "Lifetime Orders",
    "Joined Date",
  ];

  const rows = users.map((u) => [
    u.full_name,
    u.email,
    u.role,
    u.kyc_status,
    u.csd_account || "NOT_ASSIGNED",
    Number(u.cash || 0).toFixed(2),
    u.orderCount,
    new Date(u.created_at).toISOString().slice(0, 10),
  ]);

  const totalsRow = [
    "TOTALS / SUMMARY",
    `${users.length} Registered Investors`,
    "—",
    `${approvedKycCount} KYC Verified`,
    "—",
    totalCash.toFixed(2),
    users.reduce((s, u) => s + (Number(u.orderCount) || 0), 0),
    "—",
  ];

  downloadFormattedCsv({
    filename: `constant-capital-investor-registry-${dateStr}.csv`,
    reportTitle: "Client Investment Registry & KYC Compliance Report",
    periodLabel,
    headers,
    rows,
    totalsRow,
    metadata: {
      "Total Investor Cash Reserves": `GHS ${totalCash.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      "Approved KYC Proportion": `${Math.round((approvedKycCount / (users.length || 1)) * 100)}%`,
    },
  });
}

/**
 * Formatted Financial & Revenue Ledger Export
 */
export function exportFinancialLedgerReport(
  m: AdminMetrics,
  volumeByClass: { name: string; value: number }[] = [],
  periodLabel = "All Time",
) {
  const dateStr = new Date().toISOString().slice(0, 10);
  const secLevy = m.turnover * 0.0018; // 0.18%
  const gseLevy = m.turnover * 0.0022; // 0.22%
  const csdLevy = m.turnover * 0.0005; // 0.05%
  const netCommission = m.revenue - (secLevy + gseLevy + csdLevy);

  const headers = [
    "Financial Metric Category",
    "Description",
    "Rate / Basis",
    "Notional Value (GHS)",
    "Status / Notes",
  ];

  const rows = [
    ["Turnover (Filled Orders)", "Total matched & executed trade notional", "Gross Trade Value", m.turnover.toFixed(2), "Settled / Active"],
    ["Total Assets Under Management (AUM)", "Combined platform holdings + liquid cash reserves", "AUM Gross", m.aum.toFixed(2), "Custody Value"],
    ["Liquid Cash Reserves", "Total aggregate client wallet cash balances", "Uninvested Capital", m.cashReserves.toFixed(2), "Held in Trust Account"],
    ["Brokerage Gross Commission", "Gross firm trading fees before market levies", "≈ 1.15%", m.revenue.toFixed(2), "Earned Revenue"],
    ["GSE Market Transaction Fee", "Ghana Stock Exchange statutory exchange fee", "0.22%", gseLevy.toFixed(2), "Statutory Levy"],
    ["SEC Regulatory Levy", "Securities & Exchange Commission investor protection levy", "0.18%", secLevy.toFixed(2), "Statutory Levy"],
    ["CSD Settlement Fee", "Central Securities Depository trade clearing fee", "0.05%", csdLevy.toFixed(2), "Statutory Levy"],
    ["Net Brokerage Margin", "Net firm retained commission after market levies", "≈ 0.70%", Math.max(netCommission, 0).toFixed(2), "Net Operating Margin"],
    ...volumeByClass.map((vc) => [
      `Asset Class Volume: ${vc.name}`,
      `Gross turnover within ${vc.name}`,
      `${((vc.value / (m.turnover || 1)) * 100).toFixed(1)}% of Turnover`,
      vc.value.toFixed(2),
      "Asset Class Breakdown",
    ]),
  ];

  downloadFormattedCsv({
    filename: `constant-capital-financial-ledger-${dateStr}.csv`,
    reportTitle: "Executive Financial & Revenue Reconciliation Ledger",
    periodLabel,
    headers,
    rows,
    metadata: {
      "Firm Gross AUM": formatGHS(m.aum),
      "Turnover Notional": formatGHS(m.turnover),
      "Gross Fee Revenue": formatGHS(m.revenue),
    },
  });
}

/**
 * Formatted Audit Logs Export
 */
export function exportAuditLogsReport(logs: AdminAuditLog[], periodLabel = "All Time") {
  const dateStr = new Date().toISOString().slice(0, 10);
  const headers = [
    "Log ID",
    "Timestamp (UTC)",
    "Action",
    "Initiator Name",
    "Initiator Email",
    "Entity Reference",
    "Event Details",
  ];

  const rows = logs.map((log) => [
    log.id,
    new Date(log.createdAt).toISOString().replace("T", " ").slice(0, 19),
    log.action,
    log.user ? `${log.user.firstName || ""} ${log.user.lastName || ""}`.trim() || "SYSTEM" : "SYSTEM",
    log.user?.email || "system@constantcapital.com.gh",
    log.entityId || "N/A",
    log.details ? JSON.stringify(log.details) : "",
  ]);

  downloadFormattedCsv({
    filename: `constant-capital-audit-trail-${dateStr}.csv`,
    reportTitle: "System Audit & Regulatory Compliance Trail",
    periodLabel,
    headers,
    rows,
    metadata: {
      "Audit Entries Captured": logs.length,
      "Compliance Standard": "SEC Ghana AML/CFT Act & GSE Trading Rules",
    },
  });
}

/**
 * Formatted Auction Bids Export
 */
export function exportAuctionBidsReport(bids: AdminBid[], periodLabel = "All Time") {
  const dateStr = new Date().toISOString().slice(0, 10);
  const totalAmount = bids.reduce((s, b) => s + Number(b.amount || 0), 0);
  const totalAllotted = bids.reduce((s, b) => s + Number(b.allottedAmount || 0), 0);

  const headers = [
    "Bid Reference",
    "Security Type",
    "Instrument Name",
    "ISIN",
    "Bid Amount (GHS)",
    "Discount / Yield Rate (%)",
    "Status",
    "Allotted Amount (GHS)",
    "Placed Timestamp",
  ];

  const rows = bids.map((b) => [
    b.id,
    b.auction?.securityType || "TREASURY_BILL",
    b.auction?.instrumentName || "Government of Ghana Tender",
    b.auction?.isin || "N/A",
    Number(b.amount || 0).toFixed(2),
    Number(b.rate || 0).toFixed(4),
    b.status.toUpperCase(),
    b.allottedAmount ? Number(b.allottedAmount).toFixed(2) : "0.00",
    new Date(b.createdAt).toISOString().replace("T", " ").slice(0, 19),
  ]);

  const totalsRow = [
    "TOTALS / SUMMARY",
    `${bids.length} Submitted Bids`,
    "—",
    "—",
    totalAmount.toFixed(2),
    "—",
    "—",
    totalAllotted.toFixed(2),
    "—",
  ];

  downloadFormattedCsv({
    filename: `constant-capital-t-bill-bid-book-${dateStr}.csv`,
    reportTitle: "GSE Primary Market & T-Bill Auction Bid Book",
    periodLabel,
    headers,
    rows,
    totalsRow,
    metadata: {
      "Total Bid Face Value": `GHS ${totalAmount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      "Total Allotted Value": `GHS ${totalAllotted.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    },
  });
}
