// ─── Shared option lists for the KYC wizard ─────────────────────────────────
// Keeps StepForm clean and makes it easy to maintain as requirements change.
// The user can still type a custom value when a field uses a datalist/combobox.

export const COUNTRIES = [
  "Ghana",
  "Nigeria",
  "South Africa",
  "Kenya",
  "United Kingdom",
  "United States",
  "Canada",
  "Germany",
  "France",
  "Netherlands",
  "Switzerland",
  "China",
  "India",
  "Japan",
  "Australia",
  "Italy",
  "Spain",
  "Brazil",
  "UAE",
  "Saudi Arabia",
  "Côte d'Ivoire",
  "Cameroon",
  "Senegal",
  "Tanzania",
  "Uganda",
  "Ethiopia",
  "Rwanda",
  "Egypt",
  "Morocco",
  "Togo",
  "Burkina Faso",
  "Benin",
  "Mali",
  "Niger",
  "Liberia",
  "Sierra Leone",
  "Gambia",
  "Guinea",
  "Angola",
  "Mozambique",
  "Zambia",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "Malawi",
  "DR Congo",
  "Republic of Congo",
  "Gabon",
  "Equatorial Guinea",
  "Chad",
  "Central African Republic",
  "Somalia",
  "Djibouti",
  "Eritrea",
  "Sudan",
  "South Sudan",
  "Libya",
  "Tunisia",
  "Algeria",
  "Mauritania",
  "Cape Verde",
  "São Tomé and Príncipe",
  "Comoros",
  "Mauritius",
  "Seychelles",
  "Madagascar",
  "Lesotho",
  "Eswatini",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Belgium",
  "Austria",
  "Portugal",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Greece",
  "Turkey",
  "Russia",
  "Ukraine",
  "Israel",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "South Korea",
  "Taiwan",
  "Hong Kong",
  "New Zealand",
  "Mexico",
  "Colombia",
  "Argentina",
  "Chile",
  "Peru",
  "Ecuador",
  "Venezuela",
  "Cuba",
  "Jamaica",
  "Trinidad and Tobago",
  "Barbados",
  "Bahamas",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Myanmar",
  "Cambodia",
  "Laos",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Jordan",
  "Lebanon",
  "Iraq",
  "Iran",
  "Afghanistan",
] as const;

export const GHANA_CITIES = [
  "Accra",
  "Kumasi",
  "Tamale",
  "Takoradi",
  "Tema",
  "Cape Coast",
  "Sekondi",
  "Sunyani",
  "Koforidua",
  "Ho",
  "Bolgatanga",
  "Wa",
  "Techiman",
  "Obuasi",
  "Nkawkaw",
  "Winneba",
  "Tarkwa",
  "Ejura",
  "Bawku",
  "Hohoe",
  "Aflao",
  "Nsawam",
  "Suhum",
  "Kasoa",
  "Madina",
  "Ashaiman",
  "Teshie",
  "Nungua",
  "East Legon",
  "Spintex",
  "Dansoman",
  "Achimota",
  "Dome",
  "Kpone",
  "Prampram",
  "Sogakope",
  "Keta",
  "Axim",
  "Berekum",
  "Dormaa Ahenkro",
  "Goaso",
  "Mampong",
  "Konongo",
  "Agona Swedru",
  "Mankessim",
  "Saltpond",
  "Elmina",
  "Akim Oda",
  "Kintampo",
  "Damongo",
  "Yendi",
  "Navrongo",
  "Wenchi",
  "Bibiani",
  "Dunkwa-on-Offin",
] as const;

export const OCCUPATIONS = [
  "Accountant",
  "Architect",
  "Banker",
  "Business Owner",
  "Civil Servant",
  "Consultant",
  "Dentist",
  "Doctor",
  "Driver",
  "Economist",
  "Educator / Teacher",
  "Engineer",
  "Entrepreneur",
  "Farmer",
  "Financial Analyst",
  "Graphic Designer",
  "Human Resources",
  "IT Professional",
  "Journalist",
  "Lawyer",
  "Lecturer",
  "Manager",
  "Marketing Professional",
  "Mechanic",
  "Medical Professional",
  "Military / Security",
  "Nurse",
  "Pharmacist",
  "Pilot",
  "Police Officer",
  "Professor",
  "Project Manager",
  "Real Estate Agent",
  "Researcher",
  "Sales Representative",
  "Software Developer",
  "Student",
  "Surveyor",
  "Trader / Merchant",
  "Veterinarian",
] as const;

export const PROFESSIONS = [
  "Accounting & Finance",
  "Agriculture & Farming",
  "Architecture & Construction",
  "Arts & Entertainment",
  "Banking & Financial Services",
  "Education & Training",
  "Engineering",
  "Government & Public Service",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Information Technology",
  "Insurance",
  "Law & Legal Services",
  "Manufacturing",
  "Marketing & Advertising",
  "Media & Communications",
  "Mining & Resources",
  "Non-Profit / NGO",
  "Oil & Gas / Energy",
  "Real Estate",
  "Retail & Commerce",
  "Science & Research",
  "Security Services",
  "Telecommunications",
  "Transportation & Logistics",
] as const;

export const INDUSTRIES = [
  "Agriculture",
  "Automotive",
  "Banking & Finance",
  "Construction",
  "Consulting",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "FMCG / Consumer Goods",
  "Government",
  "Healthcare / Pharmaceutical",
  "Hospitality / Tourism",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Manufacturing",
  "Mining & Extractives",
  "Non-Profit / NGO",
  "Oil & Gas",
  "Real Estate & Property",
  "Retail & Wholesale",
  "Telecommunications",
  "Transportation & Logistics",
] as const;

export const RELATIONSHIPS = [
  "Spouse",
  "Parent",
  "Sibling",
  "Child",
  "Friend",
  "Colleague",
  "Guardian",
  "Relative",
  "Partner",
] as const;

export const INVESTMENT_OBJECTIVE_SUGGESTIONS = [
  "Capital preservation and steady income",
  "Long-term wealth building through diversified investments",
  "Regular income from fixed-income securities",
  "Growth through equity investments in the Ghana Stock Exchange",
  "Saving towards retirement",
  "Building an emergency fund through low-risk instruments",
  "Diversifying my portfolio with both equities and fixed income",
  "Short-term gains from Treasury bill investments",
] as const;
