// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://spb-t4n17pcgk0r63x34.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG4xN3BjZ2swcjYzeDM0IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODY5NzI3MDcsImV4cCI6MjEwMjU0ODcwN30.iMTcIrqQuDR80EE2I4bth0OgM1KNwJJEofuPpw18fl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
